name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker build --build-arg BEAT=journalbeat --tag journalbeat:$(date +%s) .
           docker image inspect journalbeat:$(date +%s)
