
name: Cross compile Elastic Beats

on:
  - push
  - workflow_dispatch
    

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:

      - name: Get latest version number from docker hub (they have a nice API)
        id: version
        run: |
          version = $(curl 'https://hub.docker.com/v2/repositories/elastic/journalbeat/tags?page_size=1' | jq -r .results[0].name)
          echo "::set-output name=name::v$version"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${steps.version.outputs.name}
