
name: Cross compile Elastic Beats

on:
  - push
  - workflow_dispatch
    

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:

      - uses: octokit/request-action@v2.x
        id: latest_release
        with:
          route: GET /repos/elastic/beats/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse json release file
        id: release
        run: |
          tag_name=$(echo "$release" | jq -r '.tag_name')
          echo "::set-output name=tag_name::$tag_name"
        env:
          release : ${{ steps.latest_release.outputs.data }}
   
      - uses: actions/checkout@v2
        with:
          repository:  elastic/beats
          ref:  ${{ steps.release.outputs.tag_name }}

